name: Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Package Boot module
        run: mvn -B -pl boot -am package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-jar
          path: boot/target/*.jar
